export const CHANGE_POSITION_POPUP = "CHANGE_POSITION_POPUP";
export const ADD_POSITION_POPUP = "ADD_POSITION_POPUP";
export const EDIT_POSITION_POPUP = "EDIT_POSITION_POPUP";
export const ADD_COMPETENCY_POPUP = "ADD_COMPETENCY_POPUP";
export const EDIT_COMPETENCY_POPUP = "EDIT_COMPETENCY_POPUP";
export const ADD_BLOCK_POPUP = "ADD_BLOCK_POPUP";
export const EDIT_BLOCK_POPUP = "EDIT_BLOCK_POPUP";
