export const EMPLOYEE_ENTITY = "EMPLOYEE_ENTITY";
export const EMPLOYEES_ENTITY = "EMPLOYEES_ENTITY";
export const DIVISIONS_ENTITY = "DIVISIONS_ENTITY";
export const ASSESSMENT_TABLE_ENTITY = "ASSESSMENT_TABLE_ENTITY";
export const CHANGE_POSITION_ENTITY = "CHANGE_POSITION_ENTITY";
