export const FETCH_LOADING = "FETCH_LOADING";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const CHANGE_EMPLOYEE_POSITION = "CHANGE_EMPLOYEE_POSITION";
export const RESET_REDUCER = "RESET_REDUCER";
export const SET_NEW_USER_POSITION = "SET_NEW_USER_POSITION";
